# Generated by Django 2.1.7 on 2019-03-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainControllerApp', '0002_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='hasparams',
            field=models.BooleanField(default=False),
        ),
    ]
