# Generated by Django 2.1.7 on 2019-03-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainControllerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('p50xa', models.CharField(max_length=100, unique=True)),
                ('p50xb', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
    ]
