# Generated by Django 2.1.7 on 2019-04-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainControllerApp', '0004_profile'),
        ('TrainControllerApp', '0004_train_user'),
    ]

    operations = [
    ]
